### ISSUE TITLE
已经用不了了，请查看

### ISSUE THREAD

**Issue by kannys** [NoBey/Shadowsocks-free#17]

**Comment by Queequeg92** [comment]
@kannys ss1.nobey.cn正常啊

**Comment by kannys** [comment]
ss.nobey.cn <http://ss.nobey.cn/> and ss1.nobey.cn <http://ss1.nobey.cn/>
我都试过，但是翻墙是不行了，google都打不开

**Comment by NoBey** [comment]
ss1 ，我这里很正常，看youtube 都不卡 @kannys

**Comment by kannys** [comment]
能否把你的配置发给我看一下

按照你们的配置
ss1.nobey.cn <http://ss1.nobey.cn/>
端口：9000
密码：nobey

不过我这边连google都上不去，哈哈

**Comment by gfw-breaker** [comment]
来这里，长期更新 [https://github.com/gfw-breaker/ssr-accounts](https://github.com/gfw-breaker/ssr-accounts)
